language: python

before_install:
  - pip install codecov

install:
  - pip install tox

script: tox -e $TOX_ENV
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOX_ENV=py35-django19
    - python: "3.4"
      env: TOX_ENV=py34-django19
    - python: "2.7"
      env: TOX_ENV=py27-django19
    - python: "3.5"
      env: TOX_ENV=py35-django18
    - python: "3.4"
      env: TOX_ENV=py34-django18
    - python: "3.3"
      env: TOX_ENV=py33-django18
    - python: "2.7"
      env: TOX_ENV=py27-django18
    - python: "2.7"
      env: TOX_ENV=lint

after_success:
  - codecov -e TOX_ENV

deploy:
  provider: pypi
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    condition: "$TOXENV = py27-django19"
    repo: jamieconnolly/django-lazy-choices
    tags: true

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip
sudo: false
